const ONE_MINUTE = 60000;
const IDLE_TIME = 15;
const EXPIRED_TIME = 15;

export const IDLESTATUS_AWAY = 'AWAY';
export const IDLESTATUS_AWAY_TIME = IDLE_TIME * ONE_MINUTE;
export const IDLESTATUS_EXPIRED = 'EXPIRED';
export const IDLESTATUS_EXPIRED_TIME = EXPIRED_TIME * ONE_MINUTE;

export const IDLE_STATUSES = [IDLESTATUS_AWAY, IDLESTATUS_EXPIRED];
